version: '3.8'

services:
  todo-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./todo.db
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
    depends_on:
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery-worker:
    build: .
    environment:
      - DATABASE_URL=sqlite:///./todo.db
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
    depends_on:
      - redis
    command: celery -A app.celery_tasks.worker worker -l info

  celery-flower:
    build: .
    ports:
      - "5555:5555"
    environment:
      - DATABASE_URL=sqlite:///./todo.db
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
    depends_on:
      - redis
    command: celery -A app.celery_tasks.worker flower --port=5555

volumes:
  redis_data:
