"""Add hierarchical ID structure

Revision ID: 41f72c6474f3
Revises: 
Create Date: 2025-10-19 04:53:07.778672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41f72c6474f3'
down_revision: Union[str, Sequence[str], None] = '000000000000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # まずNULLABLEカラムを追加
    op.add_column('tasks', sa.Column('hierarchical_id', sa.String(length=255), nullable=True))
    op.add_column('tasks', sa.Column('type', sa.Enum('requirement', 'task', 'subtask', name='tasktype'), nullable=True))
    op.add_column('tasks', sa.Column('parent_id', sa.Integer(), nullable=True))
    
    # 既存のレコードにデフォルト値を設定
    op.execute("UPDATE tasks SET type = 'task' WHERE type IS NULL")
    op.execute("UPDATE tasks SET hierarchical_id = 'LEGACY-' || id WHERE hierarchical_id IS NULL")
    
    # NOT NULL制約を追加
    op.alter_column('tasks', 'type', nullable=False)
    op.alter_column('tasks', 'hierarchical_id', nullable=False)
    
    # インデックスと外部キーを追加
    op.create_index(op.f('ix_tasks_hierarchical_id'), 'tasks', ['hierarchical_id'], unique=True)
    op.create_foreign_key(None, 'tasks', 'tasks', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_hierarchical_id'), table_name='tasks')
    op.drop_column('tasks', 'parent_id')
    op.drop_column('tasks', 'type')
    op.drop_column('tasks', 'hierarchical_id')
    # ### end Alembic commands ###
